### PR TITLE
fix: burning progress

### LINKED ISSUE #368: PoolProgress > burning error
- "claim all" is not working. when clicked, toast shows up (all receipts are claimed)
  - it seems like same cards repeated (same id)
  - the number (top right in card) changes when burn one of them.

image

image

### PR DESCRIPTION
**Pull request by kayden-fi**
Fixes #368

### CODE REVIEW

**Review by austin-builds — COMMENTED** [review]
## Comment

- My share of burned CLB (Ratio)
  - CLB Amount on a receipt / CLB Amount Requested to be burned

- My burned CLB amount
  - Ratio * Burning CLB amount

- The burned settlement token amount
  - Ratio * Burning token amount

File: src/stories/molecule/PoolProgress/index.tsx [hunk 1]
```diff
@@ -28,20 +30,20 @@ const formatter = Intl.NumberFormat('en', {
...
   }
-  const amountRatio = amount !== 0n ? divPreserved(burningAmount, amount, 2) : 0n;
+  
   return `${formatDecimals(burningAmount, token.decimals, 2, true)} / ${formatDecimals(
     amount,
     token.decimals,
     2,
     true
-  )} (${formatter.format(amountRatio)}%)`;
+  )} ${token.name} (${formatter.format(progressPercent)}%)`;
```
Comment (austin-builds) [inline src/stories/molecule/PoolProgress/index.tsx:46]: Receipts that are completed to burn could show token name twice.
